/*
  Warnings:

  - The values [LEAD_CREATED] on the enum `Log_type` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `log` MODIFY `type` ENUM('LEAD_ASSIGNED', 'LEAD_STATUS_CHANGED', 'NOTE_ADDED', 'FILE_UPLOADED', 'LEAD_TRANSFERRED', 'LEAD_CONTACT', 'CALL_REMINDER_CREATED', 'CALL_REMINDER_STATUS', 'PRICE_OFFER_SUBMITTED', 'PRICE_OFFER_UPDATED', 'FINAL_PRICE_ADDED', 'FINAL_PRICE_CHANGED', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `notification` ADD COLUMN `contentType` ENUM('TEXT', 'HTML') NOT NULL DEFAULT 'TEXT',
    MODIFY `type` ENUM('NEW_LEAD', 'LEAD_ASSIGNED', 'LEAD_STATUS_CHANGE', 'LEAD_TRANSFERRED', 'LEAD_UPDATED', 'NEW_NOTE', 'NEW_FILE', 'NEW_REMINDER', 'NEW_LOG') NOT NULL;
