export const Emirate = {
  DUBAI: "Dubai",
  ABU_DHABI: "Abu Dhabi",
  SHARJAH: "Sharjah",
  AJMAN: "Ajman",
  UMM_AL_QUWAIN: "Umm Al Quwain",
  RAS_AL_KHAIMAH: "Ras Al Khaimah",
  FUJAIRAH: "Fujairah",
  KHOR_FAKKAN: "Khor Fakkan",
};

export const countriesByRegion = {
  Asia: [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "Cyprus",
    "Georgia",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Israel",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Lebanon",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "North Korea",
    "Oman",
    "Pakistan",
    "Palestine",
    "Philippines",
    "Qatar",
    "Saudi Arabia",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "Timor-Leste",
    "Turkey",
    "Turkmenistan",
    "United Arab Emirates",
    "Uzbekistan",
    "Vietnam",
    "Yemen",
  ],
  Europe: [
    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "United Kingdom",
    "Vatican City",
  ],
  Africa: [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
  ],
  "North America": [
    "Antigua and Barbuda",
    "Bahamas",
    "Barbados",
    "Belize",
    "Canada",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "El Salvador",
    "Grenada",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "United States",
  ],
  "South America": [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela",
  ],
  Oceania: [
    "Australia",
    "Fiji",
    "Kiribati",
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "New Zealand",
    "Palau",
    "Papua New Guinea",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
  ],
};

export const LEAD_SOURCE_LABELS = {
  INSTAGRAM: { en: "Instagram", ar: "انستغرام" },
  TIKTOK: { en: "TikTok", ar: "تيك توك" },
  TV: { en: "TV", ar: "تلفاز" },
  FACEBOOK: { en: "Facebook", ar: "فيسبوك" },
  YOUTUBE: { en: "YouTube", ar: "يوتيوب" },
  GOOGLE: { en: "Google", ar: "جوجل" },
  INTERIOR_MAGAZINE_SITE: {
    en: "Interior design magazine/site",
    ar: "مجلة/موقع تصميم داخلي",
  },
  REFERRAL: {
    en: "Referral from friend or previous client",
    ar: "توصية من صديق أو عميل سابق",
  },
  OTHER: { en: "Other", ar: "أخرى" },
};

export const UAE_LABEL = {
  ar: "الإمارات العربية المتحدة",
  en: "United Arab Emirates",
};
export const EMIRATE_LABEL = {
  ar: {
    DUBAI: "دبي",
    ABU_DHABI: "أبوظبي",
    SHARJAH: "الشارقة",
    AJMAN: "عجمان",
    UMM_AL_QUWAIN: "أم القيوين",
    RAS_AL_KHAIMAH: "رأس الخيمة",
    FUJAIRAH: "الفجيرة",
    KHOR_FAKKAN: "خورفكان",
    OUTSIDE: "خارج الإمارات",
  },
  en: {
    DUBAI: "Dubai",
    ABU_DHABI: "Abu Dhabi",
    SHARJAH: "Sharjah",
    AJMAN: "Ajman",
    UMM_AL_QUWAIN: "Umm Al Quwain",
    RAS_AL_KHAIMAH: "Ras Al Khaimah",
    FUJAIRAH: "Fujairah",
    KHOR_FAKKAN: "Khor Fakkan",
    OUTSIDE: "Outside UAE",
  },
};

export const COUNTRY_LABEL = {
  "United Arab Emirates": {
    ar: "الإمارات العربية المتحدة",
    en: "United Arab Emirates",
  },

  // Asia
  Afghanistan: { ar: "أفغانستان", en: "Afghanistan" },
  Armenia: { ar: "أرمينيا", en: "Armenia" },
  Azerbaijan: { ar: "أذربيجان", en: "Azerbaijan" },
  Bahrain: { ar: "البحرين", en: "Bahrain" },
  Bangladesh: { ar: "بنغلاديش", en: "Bangladesh" },
  Bhutan: { ar: "بوتان", en: "Bhutan" },
  Brunei: { ar: "بروناي", en: "Brunei" },
  Cambodia: { ar: "كمبوديا", en: "Cambodia" },
  China: { ar: "الصين", en: "China" },
  Cyprus: { ar: "قبرص", en: "Cyprus" },
  Georgia: { ar: "جورجيا", en: "Georgia" },
  India: { ar: "الهند", en: "India" },
  Indonesia: { ar: "إندونيسيا", en: "Indonesia" },
  Iran: { ar: "إيران", en: "Iran" },
  Iraq: { ar: "العراق", en: "Iraq" },
  Israel: { ar: "إسرائيل", en: "Israel" },
  Japan: { ar: "اليابان", en: "Japan" },
  Jordan: { ar: "الأردن", en: "Jordan" },
  Kazakhstan: { ar: "كازاخستان", en: "Kazakhstan" },
  Kuwait: { ar: "الكويت", en: "Kuwait" },
  Kyrgyzstan: { ar: "قرغيزستان", en: "Kyrgyzstan" },
  Laos: { ar: "لاوس", en: "Laos" },
  Lebanon: { ar: "لبنان", en: "Lebanon" },
  Malaysia: { ar: "ماليزيا", en: "Malaysia" },
  Maldives: { ar: "المالديف", en: "Maldives" },
  Mongolia: { ar: "منغوليا", en: "Mongolia" },
  Myanmar: { ar: "ميانمار", en: "Myanmar" },
  Nepal: { ar: "نيبال", en: "Nepal" },
  "North Korea": { ar: "كوريا الشمالية", en: "North Korea" },
  Oman: { ar: "عُمان", en: "Oman" },
  Pakistan: { ar: "باكستان", en: "Pakistan" },
  Palestine: { ar: "فلسطين", en: "Palestine" },
  Philippines: { ar: "الفلبين", en: "Philippines" },
  Qatar: { ar: "قطر", en: "Qatar" },
  "Saudi Arabia": { ar: "المملكة العربية السعودية", en: "Saudi Arabia" },
  Singapore: { ar: "سنغافورة", en: "Singapore" },
  "South Korea": { ar: "كوريا الجنوبية", en: "South Korea" },
  "Sri Lanka": { ar: "سريلانكا", en: "Sri Lanka" },
  Syria: { ar: "سوريا", en: "Syria" },
  Taiwan: { ar: "تايوان", en: "Taiwan" },
  Tajikistan: { ar: "طاجيكستان", en: "Tajikistan" },
  Thailand: { ar: "تايلاند", en: "Thailand" },
  "Timor-Leste": { ar: "تيمور الشرقية", en: "Timor-Leste" },
  Turkey: { ar: "تركيا", en: "Turkey" },
  Turkmenistan: { ar: "تركمانستان", en: "Turkmenistan" },
  Uzbekistan: { ar: "أوزبكستان", en: "Uzbekistan" },
  Vietnam: { ar: "فيتنام", en: "Vietnam" },
  Yemen: { ar: "اليمن", en: "Yemen" },

  // Europe
  Albania: { ar: "ألبانيا", en: "Albania" },
  Andorra: { ar: "أندورا", en: "Andorra" },
  Austria: { ar: "النمسا", en: "Austria" },
  Belarus: { ar: "بيلاروسيا", en: "Belarus" },
  Belgium: { ar: "بلجيكا", en: "Belgium" },
  "Bosnia and Herzegovina": {
    ar: "البوسنة والهرسك",
    en: "Bosnia and Herzegovina",
  },
  Bulgaria: { ar: "بلغاريا", en: "Bulgaria" },
  Croatia: { ar: "كرواتيا", en: "Croatia" },
  "Czech Republic": { ar: "جمهورية التشيك", en: "Czech Republic" },
  Denmark: { ar: "الدنمارك", en: "Denmark" },
  Estonia: { ar: "إستونيا", en: "Estonia" },
  Finland: { ar: "فنلندا", en: "Finland" },
  France: { ar: "فرنسا", en: "France" },
  Germany: { ar: "ألمانيا", en: "Germany" },
  Greece: { ar: "اليونان", en: "Greece" },
  Hungary: { ar: "المجر", en: "Hungary" },
  Iceland: { ar: "آيسلندا", en: "Iceland" },
  Ireland: { ar: "أيرلندا", en: "Ireland" },
  Italy: { ar: "إيطاليا", en: "Italy" },
  Kosovo: { ar: "كوسوفو", en: "Kosovo" },
  Latvia: { ar: "لاتفيا", en: "Latvia" },
  Liechtenstein: { ar: "ليختنشتاين", en: "Liechtenstein" },
  Lithuania: { ar: "ليتوانيا", en: "Lithuania" },
  Luxembourg: { ar: "لوكسمبورغ", en: "Luxembourg" },
  Malta: { ar: "مالطا", en: "Malta" },
  Moldova: { ar: "مولدوفا", en: "Moldova" },
  Monaco: { ar: "موناكو", en: "Monaco" },
  Montenegro: { ar: "الجبل الأسود", en: "Montenegro" },
  Netherlands: { ar: "هولندا", en: "Netherlands" },
  "North Macedonia": { ar: "مقدونيا الشمالية", en: "North Macedonia" },
  Norway: { ar: "النرويج", en: "Norway" },
  Poland: { ar: "بولندا", en: "Poland" },
  Portugal: { ar: "البرتغال", en: "Portugal" },
  Romania: { ar: "رومانيا", en: "Romania" },
  Russia: { ar: "روسيا", en: "Russia" },
  "San Marino": { ar: "سان مارينو", en: "San Marino" },
  Serbia: { ar: "صربيا", en: "Serbia" },
  Slovakia: { ar: "سلوفاكيا", en: "Slovakia" },
  Slovenia: { ar: "سلوفينيا", en: "Slovenia" },
  Spain: { ar: "إسبانيا", en: "Spain" },
  Sweden: { ar: "السويد", en: "Sweden" },
  Switzerland: { ar: "سويسرا", en: "Switzerland" },
  Ukraine: { ar: "أوكرانيا", en: "Ukraine" },
  "United Kingdom": { ar: "المملكة المتحدة", en: "United Kingdom" },
  "Vatican City": { ar: "مدينة الفاتيكان", en: "Vatican City" },

  // Africa
  Algeria: { ar: "الجزائر", en: "Algeria" },
  Angola: { ar: "أنغولا", en: "Angola" },
  Benin: { ar: "بنين", en: "Benin" },
  Botswana: { ar: "بوتسوانا", en: "Botswana" },
  "Burkina Faso": { ar: "بوركينا فاسو", en: "Burkina Faso" },
  Burundi: { ar: "بوروندي", en: "Burundi" },
  "Cabo Verde": { ar: "الرأس الأخضر", en: "Cabo Verde" },
  Cameroon: { ar: "الكاميرون", en: "Cameroon" },
  "Central African Republic": {
    ar: "جمهورية أفريقيا الوسطى",
    en: "Central African Republic",
  },
  Chad: { ar: "تشاد", en: "Chad" },
  Comoros: { ar: "جزر القمر", en: "Comoros" },
  Congo: { ar: "الكونغو", en: "Congo" },
  Djibouti: { ar: "جيبوتي", en: "Djibouti" },
  Egypt: { ar: "مصر", en: "Egypt" },
  "Equatorial Guinea": { ar: "غينيا الاستوائية", en: "Equatorial Guinea" },
  Eritrea: { ar: "إريتريا", en: "Eritrea" },
  Eswatini: { ar: "إسواتيني", en: "Eswatini" },
  Ethiopia: { ar: "إثيوبيا", en: "Ethiopia" },
  Gabon: { ar: "الغابون", en: "Gabon" },
  Gambia: { ar: "غامبيا", en: "Gambia" },
  Ghana: { ar: "غانا", en: "Ghana" },
  Guinea: { ar: "غينيا", en: "Guinea" },
  "Guinea-Bissau": { ar: "غينيا بيساو", en: "Guinea-Bissau" },
  Kenya: { ar: "كينيا", en: "Kenya" },
  Lesotho: { ar: "ليسوتو", en: "Lesotho" },
  Liberia: { ar: "ليبيريا", en: "Liberia" },
  Libya: { ar: "ليبيا", en: "Libya" },
  Madagascar: { ar: "مدغشقر", en: "Madagascar" },
  Malawi: { ar: "مالاوي", en: "Malawi" },
  Mali: { ar: "مالي", en: "Mali" },
  Mauritania: { ar: "موريتانيا", en: "Mauritania" },
  Mauritius: { ar: "موريشيوس", en: "Mauritius" },
  Morocco: { ar: "المغرب", en: "Morocco" },
  Mozambique: { ar: "موزمبيق", en: "Mozambique" },
  Namibia: { ar: "ناميبيا", en: "Namibia" },
  Niger: { ar: "النيجر", en: "Niger" },
  Nigeria: { ar: "نيجيريا", en: "Nigeria" },
  Rwanda: { ar: "رواندا", en: "Rwanda" },
  "Sao Tome and Principe": {
    ar: "ساو تومي وبرينسيبي",
    en: "Sao Tome and Principe",
  },
  Senegal: { ar: "السنغال", en: "Senegal" },
  Seychelles: { ar: "سيشل", en: "Seychelles" },
  "Sierra Leone": { ar: "سيراليون", en: "Sierra Leone" },
  Somalia: { ar: "الصومال", en: "Somalia" },
  "South Africa": { ar: "جنوب أفريقيا", en: "South Africa" },
  "South Sudan": { ar: "جنوب السودان", en: "South Sudan" },
  Sudan: { ar: "السودان", en: "Sudan" },
  Tanzania: { ar: "تنزانيا", en: "Tanzania" },
  Togo: { ar: "توغو", en: "Togo" },
  Tunisia: { ar: "تونس", en: "Tunisia" },
  Uganda: { ar: "أوغندا", en: "Uganda" },
  Zambia: { ar: "زامبيا", en: "Zambia" },
  Zimbabwe: { ar: "زيمبابوي", en: "Zimbabwe" },

  // North America
  "Antigua and Barbuda": { ar: "أنتيغوا وبربودا", en: "Antigua and Barbuda" },
  Bahamas: { ar: "جزر البهاما", en: "Bahamas" },
  Barbados: { ar: "بربادوس", en: "Barbados" },
  Belize: { ar: "بليز", en: "Belize" },
  Canada: { ar: "كندا", en: "Canada" },
  "Costa Rica": { ar: "كوستاريكا", en: "Costa Rica" },
  Cuba: { ar: "كوبا", en: "Cuba" },
  Dominica: { ar: "دومينيكا", en: "Dominica" },
  "Dominican Republic": { ar: "جمهورية الدومينيكان", en: "Dominican Republic" },
  "El Salvador": { ar: "السلفادور", en: "El Salvador" },
  Grenada: { ar: "غرينادا", en: "Grenada" },
  Guatemala: { ar: "غواتيمالا", en: "Guatemala" },
  Haiti: { ar: "هايتي", en: "Haiti" },
  Honduras: { ar: "هندوراس", en: "Honduras" },
  Jamaica: { ar: "جامايكا", en: "Jamaica" },
  Mexico: { ar: "المكسيك", en: "Mexico" },
  Nicaragua: { ar: "نيكاراغوا", en: "Nicaragua" },
  Panama: { ar: "بنما", en: "Panama" },
  "Saint Kitts and Nevis": {
    ar: "سانت كيتس ونيفيس",
    en: "Saint Kitts and Nevis",
  },
  "Saint Lucia": { ar: "سانت لوسيا", en: "Saint Lucia" },
  "Saint Vincent and the Grenadines": {
    ar: "سانت فنسنت وجزر غرينادين",
    en: "Saint Vincent and the Grenadines",
  },
  "Trinidad and Tobago": { ar: "ترينيداد وتوباغو", en: "Trinidad and Tobago" },
  "United States": { ar: "الولايات المتحدة", en: "United States" },

  // South America
  Argentina: { ar: "الأرجنتين", en: "Argentina" },
  Bolivia: { ar: "بوليفيا", en: "Bolivia" },
  Brazil: { ar: "البرازيل", en: "Brazil" },
  Chile: { ar: "تشيلي", en: "Chile" },
  Colombia: { ar: "كولومبيا", en: "Colombia" },
  Ecuador: { ar: "الإكوادور", en: "Ecuador" },
  Guyana: { ar: "غيانا", en: "Guyana" },
  Paraguay: { ar: "باراغواي", en: "Paraguay" },
  Peru: { ar: "بيرو", en: "Peru" },
  Suriname: { ar: "سورينام", en: "Suriname" },
  Uruguay: { ar: "أوروغواي", en: "Uruguay" },
  Venezuela: { ar: "فنزويلا", en: "Venezuela" },

  // Oceania
  Australia: { ar: "أستراليا", en: "Australia" },
  Fiji: { ar: "فيجي", en: "Fiji" },
  Kiribati: { ar: "كيريباتي", en: "Kiribati" },
  "Marshall Islands": { ar: "جزر مارشال", en: "Marshall Islands" },
  Micronesia: { ar: "ولايات ميكرونيزيا المتحدة", en: "Micronesia" },
  Nauru: { ar: "ناورو", en: "Nauru" },
  "New Zealand": { ar: "نيوزيلندا", en: "New Zealand" },
  Palau: { ar: "بالاو", en: "Palau" },
  "Papua New Guinea": { ar: "بابوا غينيا الجديدة", en: "Papua New Guinea" },
  Samoa: { ar: "ساموا", en: "Samoa" },
  "Solomon Islands": { ar: "جزر سليمان", en: "Solomon Islands" },
  Tonga: { ar: "تونغا", en: "Tonga" },
  Tuvalu: { ar: "توفالو", en: "Tuvalu" },
  Vanuatu: { ar: "فانواتو", en: "Vanuatu" },
};
