-- AlterTable
ALTER TABLE `clientlead` MODIFY `status` ENUM('NEW', 'IN_PROGRESS', 'INTERESTED', 'NEEDS_IDENTIFIED', 'NEGOTIATING', 'REJECTED', 'FINALIZED', 'CONVERTED', 'ON_HOLD') NOT NULL DEFAULT 'NEW';
