-- AlterTable
ALTER TABLE `clientlead` MODIFY `selectedCategory` ENUM('CONSULTATION', 'DESIGN', 'OLDLEAD') NOT NULL,
    MODIFY `type` ENUM('ROOM', 'BLUEPRINT', 'CITY_VISIT', 'APARTMENT', 'CONSTRUCTION_VILLA', 'UNDER_CONSTRUCTION_VILLA', 'PART_OF_HOME', 'COMMERCIAL', 'NONE') NOT NULL DEFAULT 'CONSTRUCTION_VILLA';
