import { Router } from "express";
import authRoutes from "../modules/auth/auth.route.js";
import { bookingLeadsRouter } from "../modules/leads/client/booking-lead/booking-leads.route.js";
import { leadRouter } from "../modules/leads/lead/lead.route.js";
import { userRouter } from "../modules/users/user/user.route.js";
import { telegramRouter } from "../modules/telegram/auth/telegram.route.js";
import { chatRouter } from "../modules/chat/chat.route.js";
import { clientChatRouter } from "../modules/chat/client/client-chat.route.js";
import { uploadRouter } from "../modules/upload/upload.route.js";
import { siteUtilityRouter } from "../modules/site-utility/site-utility.route.js";
import { adminCourseRouter } from "../modules/courses/admin-course/admin-course.route.js";
import { staffCourseRouter } from "../modules/courses/staff-course/staff-course.route.js";
import { projectRouter } from "../modules/projects/project/project.route.js";
import { taskRouter } from "../modules/projects/task/task.route.js";
import { updateRouter } from "../modules/projects/update/update.route.js";
import { deliveryRouter } from "../modules/projects/delivery/delivery.route.js";
import { accountingRouter } from "../modules/accounting/accounting.route.js";
import { calendarRouter } from "../modules/calendar/calendar.route.js";
import { clientCalendarRouter } from "../modules/calendar/client/client-calendar.route.js";
import { notificationRouter } from "../modules/notifications/notification.route.js";
import { utilityRouter } from "../modules/utilities/utility.route.js";
import { dashboardRouter } from "../modules/dashboard/dashboard.route.js";
import { questionsRouter } from "../modules/questions/questions.route.js";
import { salesStagesRouter } from "../modules/sales-stages/sales-stages.route.js";
import { reviewsRouter } from "../modules/reviews/reviews.route.js";
import { contractRouter } from "../modules/contracts/contract/contract.route.js";
import { clientContractRouter } from "../modules/contracts/client/client-contract.route.js";
import { adminImageSessionRouter } from "../modules/image-sessions/admin/admin-image-session.route.js";
import { imageSessionRouter } from "../modules/image-sessions/session/image-session.route.js";
import { clientImageSessionRouter } from "../modules/image-sessions/client/client-image-session.route.js";
import { adminResidualRouter } from "../modules/admin-residual/admin-residual.route.js";
import { staffRouter } from "../modules/admin-residual/staff/staff.route.js";
import { publicLeadRouter } from "../modules/leads/client/public-lead/public-lead.route.js";
import { clientPaymentsRouter } from "../modules/client-portal/payments/payments.route.js";
import { clientUploadsRouter } from "../modules/client-portal/uploads/uploads.route.js";
import { clientNotesRouter } from "../modules/client-portal/notes/notes.route.js";
import { clientLanguagesRouter } from "../modules/client-portal/languages/languages.route.js";
import { auditRouter } from "../modules/audit/audit.route.js";
import { myDayRouter } from "../modules/my-day/my-day.route.js";
import { genericDeleteRouter } from "../modules/generic-delete/generic-delete.route.js";
import { noteRouter } from "../modules/notes/note.route.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/delete", genericDeleteRouter);
router.use("/notes", noteRouter);
router.use("/client/booking-leads", bookingLeadsRouter);
router.use("/leads", leadRouter);
router.use("/users", userRouter);
router.use("/telegram", telegramRouter);
router.use("/chat", chatRouter);
router.use("/client/chat", clientChatRouter);
router.use("/files", uploadRouter);
router.use("/site-utilities", siteUtilityRouter);
router.use("/courses", adminCourseRouter);
router.use("/staff-courses", staffCourseRouter);
router.use("/projects", projectRouter);
router.use("/tasks", taskRouter);
router.use("/updates", updateRouter);
router.use("/delivery", deliveryRouter);
router.use("/accounting", accountingRouter);
router.use("/calendar", calendarRouter);
router.use("/calendar-management", calendarRouter);
router.use("/client/calendar", clientCalendarRouter);
router.use("/notifications", notificationRouter);
router.use("/utilities", utilityRouter);
router.use("/dashboard", dashboardRouter);
router.use("/questions", questionsRouter);
router.use("/sales-stages", salesStagesRouter);
router.use("/reviews", reviewsRouter);
router.use("/contracts", contractRouter);
router.use("/client/contracts", clientContractRouter);
router.use("/image-sessions/admin", adminImageSessionRouter);
router.use("/image-session", imageSessionRouter);
router.use("/client/image-session", clientImageSessionRouter);
router.use("/admin", adminResidualRouter);
router.use("/staff", staffRouter);
router.use("/audit-logs", auditRouter);
router.use("/my-day", myDayRouter);

// Public website and client-session surfaces.
router.use("/client", publicLeadRouter);
router.use("/client", clientPaymentsRouter);
router.use("/client", clientUploadsRouter);
router.use("/client/notes", clientNotesRouter);
router.use("/client/languages", clientLanguagesRouter);

export default router;
